wheelbase: 0.34

update_pose_rate: 0.02

scan_beams: 1000
scan_field_of_view: 4.71
scan_std_dev: 0.01

map_free_threshold: 0.3

joy_topic: "/joy"
drive_topic: "/drive"
map_topic: "/map"
distance_transform_topic: "/dt"
scan_topic: "/scan"

joy: true
joy_speed_axis: 1
joy_angle_axis: 2
joy_max_speed: 2.
joy_max_angle: 0.34
